#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Dec 03, 2018 11:07:07 AM PST  platform: Darwin

import sys

import tkinter as tk

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    root.mainloop()
    return top
class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 

        top.geometry("388x433+461+125")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        self.chatFrame = tk.Frame(top)
        self.chatFrame.place(relx=0.0, rely=0.0, relheight=0.982, relwidth=0.992)

        self.chatFrame.configure(relief='groove')
        self.chatFrame.configure(borderwidth="2")
        self.chatFrame.configure(relief='groove')
        self.chatFrame.configure(background="#d9d9d9")
        self.chatFrame.configure(width=385)



        self.msgTextBox = tk.Text(self.chatFrame)
        self.msgTextBox.place(relx=0.026, rely=0.8, relheight=0.193
                , relwidth=0.774)
        self.msgTextBox.configure(background="white")
        self.msgTextBox.configure(font="TkTextFont")
        self.msgTextBox.configure(foreground="black")
        self.msgTextBox.configure(highlightbackground="#d9d9d9")
        self.msgTextBox.configure(highlightcolor="black")
        self.msgTextBox.configure(insertbackground="black")
        self.msgTextBox.configure(selectbackground="#c4c4c4")
        self.msgTextBox.configure(selectforeground="black")
        self.msgTextBox.configure(width=298)
        self.msgTextBox.configure(wrap='word')
        

        self.sendButton = tk.Button(self.chatFrame)
        self.sendButton.place(relx=0.805, rely=0.871, height=22, width=71)
        self.sendButton.configure(activebackground="#ececec")
        self.sendButton.configure(activeforeground="#000000")
        self.sendButton.configure(background="#d9d9d9")
        
        self.sendButton.configure(foreground="#000000")
        self.sendButton.configure(highlightbackground="#d9d9d9")
        self.sendButton.configure(highlightcolor="black")
        self.sendButton.configure(text='''Send''')
        self.sendButton.configure(width=71)

        
        self.displayTextBox = tk.Text(self.chatFrame)
        self.displayTextBox.place(relx=0.0, rely=0.024, relheight=0.758
                , relwidth=0.982)
        self.displayTextBox.configure(background="#000000")
        self.displayTextBox.configure(font="TkTextFont")
        self.displayTextBox.configure(foreground="#ffffff")
        self.displayTextBox.configure(highlightbackground="#d9d9d9")
        self.displayTextBox.configure(highlightcolor="black")
        self.displayTextBox.configure(insertbackground="black")
        self.displayTextBox.configure(selectbackground="#c4c4c4")
        self.displayTextBox.configure(selectforeground="black")
        self.displayTextBox.configure(state='disabled')
        self.displayTextBox.configure(width=378)
        self.displayTextBox.configure(wrap='word')

        def addmsg():
            text = self.msgTextBox.get("1.0", tk.END)
            self.msgTextBox.delete("1.0", tk.END)
            self.displayTextBox.configure(state="normal")
            self.displayTextBox.insert(tk.END,text)
            self.displayTextBox.configure(state="disabled")

        self.sendButton.configure(command=addmsg)
if __name__ == '__main__':  
    top = vp_start_gui()


