import socket
import sys
import select
import threading

from tcp_packet_pb2 import TcpPacket
from player_pb2 import Player

HOST = '202.92.144.45'
PORT = 80

server_address = (HOST, PORT)
#INSTANTIATE A SOCKET
socket = socket.socket()
#CONNECT TO SERVER
socket.connect(server_address)
#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Dec 03, 2018 11:07:07 AM PST  platform: Darwin

import sys

import tkinter as tk

class chatgui:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 

        top.geometry("388x433+461+125")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        self.chatFrame = tk.Frame(top)
        self.chatFrame.place(relx=0.0, rely=0.0, relheight=0.982, relwidth=0.992)

        self.chatFrame.configure(relief='groove')
        self.chatFrame.configure(borderwidth="2")
        self.chatFrame.configure(relief='groove')
        self.chatFrame.configure(background="#d9d9d9")
        self.chatFrame.configure(width=385)



        self.msgTextBox = tk.Text(self.chatFrame)
        self.msgTextBox.place(relx=0.026, rely=0.8, relheight=0.193
                , relwidth=0.774)
        self.msgTextBox.configure(background="white")
        self.msgTextBox.configure(font="TkTextFont")
        self.msgTextBox.configure(foreground="black")
        self.msgTextBox.configure(highlightbackground="#d9d9d9")
        self.msgTextBox.configure(highlightcolor="black")
        self.msgTextBox.configure(insertbackground="black")
        self.msgTextBox.configure(selectbackground="#c4c4c4")
        self.msgTextBox.configure(selectforeground="black")
        self.msgTextBox.configure(width=298)
        self.msgTextBox.configure(wrap='word')
        

        self.sendButton = tk.Button(self.chatFrame)
        self.sendButton.place(relx=0.805, rely=0.871, height=22, width=71)
        self.sendButton.configure(activebackground="#ececec")
        self.sendButton.configure(activeforeground="#000000")
        self.sendButton.configure(background="#d9d9d9")
        
        self.sendButton.configure(foreground="#000000")
        self.sendButton.configure(highlightbackground="#d9d9d9")
        self.sendButton.configure(highlightcolor="black")
        self.sendButton.configure(text='''Send''')
        self.sendButton.configure(width=71)

        
        self.displayTextBox = tk.Text(self.chatFrame)
        self.displayTextBox.place(relx=0.0, rely=0.024, relheight=0.758
                , relwidth=0.982)
        self.displayTextBox.configure(background="#000000")
        self.displayTextBox.configure(font="TkTextFont")
        self.displayTextBox.configure(foreground="#ffffff")
        self.displayTextBox.configure(highlightbackground="#d9d9d9")
        self.displayTextBox.configure(highlightcolor="black")
        self.displayTextBox.configure(insertbackground="black")
        self.displayTextBox.configure(selectbackground="#c4c4c4")
        self.displayTextBox.configure(selectforeground="black")
        self.displayTextBox.configure(state='disabled')
        self.displayTextBox.configure(width=378)
        self.displayTextBox.configure(wrap='word')

        def addmsg():
            text = self.msgTextBox.get("1.0", tk.END)
            self.msgTextBox.delete("1.0", tk.END)
            self.displayTextBox.configure(state="normal")
            self.displayTextBox.insert(tk.END,text)
            self.displayTextBox.configure(state="disabled")
           
        self.sendButton.configure(command=lambda: var.set(1))


def make_player(player_name):
	player = Player()
	player.name = player_name
	return player

def make_lobby(packet):
	#packet.type = CREATE_LOBBY from TcpPacket, 2. FROM TCP_PACKET.PY
	lobbyPacket = packet.CreateLobbyPacket()
	lobbyPacket.type = TcpPacket.CREATE_LOBBY
	maxNumPlayers = int(input("Enter max number of players: "))
	lobbyPacket.max_players = maxNumPlayers
	
	#SEND TO SERVER
	socket.send(lobbyPacket.SerializeToString()) 
	
	#RECEIVE FROM SERVER
	data = bytearray(socket.recv(1024))
	lobbyPacket.ParseFromString(data)
	print('Received from server: ' + lobbyPacket.lobby_id)
	lobby_id = lobbyPacket.lobby_id

	return lobby_id

def connect_packet_conf(connectPacket,player,packet,choice):
	connectPacket.type = TcpPacket.CONNECT
	if choice == 1:
		lobby_id = make_lobby(packet)
	else:
		lobby_id = input("Enter lobby id: ") 
	connectPacket.lobby_id = lobby_id
	connectPacket.player.name = player.name

	return connectPacket.SerializeToString()

def connect_player_to_server(player, packet):
	connectPacket = packet.ConnectPacket()

	choice = int(input("[1] Create a Lobby \n[2] Connect to Lobby \nEnter choice: "))

	if choice == 1:
		#SEND CONNECT PACKET TO SERVER
		socket.send(connect_packet_conf(connectPacket,player,packet,choice)) 

		#RECEIVE FROM SERVER
		connect_data = bytearray(socket.recv(1024))
		connectPacket.ParseFromString(connect_data)
	else:
		connectPacket.type = TcpPacket.ERR_LDNE
		while connectPacket.type == TcpPacket.ERR_LDNE or connectPacket.type == TcpPacket.ERR_LFULL:
			try:
				#SEND CONNECT PACKET TO SERVER
				socket.send(connect_packet_conf(connectPacket,player,packet,choice)) 
				
				#RECEIVE FROM SERVER
				connect_data = bytearray(socket.recv(1024))
				connectPacket.ParseFromString(connect_data)

				if connectPacket.type == TcpPacket.ERR_LFULL:
					print("Lobby is FULL.\n")
			except:
				if connectPacket.type == TcpPacket.ERR_LDNE:
					print("Lobby DOES NOT EXIST. Try entering another lobby id.\n")
	print('Received from server: ' + str(connectPacket))
	return connectPacket

def chat_packet_conf(player,packet, lobby_id,chatPacket):
	chatPacket.type = TcpPacket.CHAT
    text = self.msgTextBox.get("1.0", tk.END)
	chatPacket.message = text
	chatPacket.player.name = player_name
	chatPacket.lobby_id = lobby_id
	var = tk.IntVar()
	button.wait_variable(var)
	return chatPacket.SerializeToString()

def chat_main(player, packet, lobby_id, connectPacket):
	global chatgui
	packet_type = 0
	while True:
		list_of_sockets = [sys.stdin, socket] 

		#FOR CHAT PACKET 
		chatPacket = packet.ChatPacket()

		#FOR DISCONNECT CHAT PACKET
		disconnectPacket = packet.DisconnectPacket()
		disconnectPacket.type = TcpPacket.DISCONNECT

		read_sockets,write_socket,error_socket = select.select(list_of_sockets,[],[])

		for socks in read_sockets: 
			if socks == socket: 
				packet_received = bytearray(socket.recv(2048))
				packet.ParseFromString(packet_received)
				packet_type = packet.type 
				
				
				# 3: CHAT
				if packet_type == 3:
					#Receive broadcasted data from server
					chatPacket.ParseFromString(packet_received)
					chatgui.addmsg
					root.update()
					print(chatPacket.player.name+": "+ chatPacket.message)

				# 1: CONNECT
				if packet_type == 1:
					connectPacket.ParseFromString(packet_received)
					print(connectPacket.player.name + " connected!")

				# 0: DISCONNECT
				if packet_type == 0: 
					disconnectPacket.ParseFromString(packet_received)
					if disconnectPacket.player.name == "":
						if disconnectPacket.update == 0:
							print("You left!")
						else:
							print("Unknown error occured.\nYou have been disconnected from the game")
						sys.exit()
					else :
						print(disconnectPacket.player.name + " left!")
			#MESSAGE
			else: 
				#SEND TO SERVER
				socket.send(chat_packet_conf(player,packet,lobby_id,chatPacket))

				if chatPacket.message.strip() == "bye" or chatPacket.message.strip() == "exit":
					disconnectPacket.type = TcpPacket.DISCONNECT

					disconnectPacket.player.name = player_name
					socket.send(disconnectPacket.SerializeToString())


packet = TcpPacket()
root = tk.Tk()
chatgui = chatgui (root)
player_name = input("Enter name: ")
player = make_player(player_name)
connectPacket = connect_player_to_server(player, packet)
chat_main(player, packet, connectPacket.lobby_id, connectPacket)
root.mainloop()
socket.close() 
